-- 优化前
WITH new_activate_active_retention AS (
    SELECT t2.day AS dt,'new_activate_active_retention' AS retention_type,user_num, user_num_0d
    , user_num_1d, user_num_2d, user_num_3d, user_num_4d, user_num_5d, user_num_6d, user_num_7d, user_num_8d
    , user_num_9d, user_num_10d, user_num_11d, user_num_12d, user_num_13d, user_num_14d, user_num_15d, user_num_16d
    , user_num_17d, user_num_18d, user_num_19d, user_num_20d, user_num_21d, user_num_22d, user_num_23d, user_num_24d
    , user_num_25d, user_num_26d, user_num_27d, user_num_28d, user_num_29d, user_num_30d, user_num_31d
    FROM 
    (
        SELECT 
            t1.day 
            ,COUNT(DISTINCT user_id) AS user_num
            ,COUNT(IF(instr(active_date_trace,day) > 0,1,NULL)) AS user_num_0d
,COUNT(IF(date_add(day,1)<='2023-09-01' AND instr(active_date_trace , date_add(day,0))+instr(active_date_trace , date_add(day,1))>0,1,NULL)) AS user_num_1d
,COUNT(IF(date_add(day,2)<='2023-09-01' AND instr(active_date_trace , date_add(day,0))+instr(active_date_trace , date_add(day,1))+instr(active_date_trace , date_add(day,2))>0,1,NULL)) AS user_num_2d
,COUNT(IF(date_add(day,3)<='2023-09-01' AND instr(active_date_trace , date_add(day,0))+instr(active_date_trace , date_add(day,1))+instr(active_date_trace , date_add(day,2))+instr(active_date_trace , date_add(day,3))>0,1,NULL)) AS user_num_3d
,COUNT(IF(date_add(day,4)<='2023-09-01' AND instr(active_date_trace , date_add(day,0))+instr(active_date_trace , date_add(day,1))+instr(active_date_trace , date_add(day,2))+instr(active_date_trace , date_add(day,3))+instr(active_date_trace , date_add(day,4))>0,1,NULL)) AS user_num_4d
,COUNT(IF(date_add(day,5)<='2023-09-01' AND instr(active_date_trace , date_add(day,0))+instr(active_date_trace , date_add(day,1))+instr(active_date_trace , date_add(day,2))+instr(active_date_trace , date_add(day,3))+instr(active_date_trace , date_add(day,4))+instr(active_date_trace , date_add(day,5))>0,1,NULL)) AS user_num_5d
,COUNT(IF(date_add(day,6)<='2023-09-01' AND instr(active_date_trace , date_add(day,0))+instr(active_date_trace , date_add(day,1))+instr(active_date_trace , date_add(day,2))+instr(active_date_trace , date_add(day,3))+instr(active_date_trace , date_add(day,4))+instr(active_date_trace , date_add(day,5))+instr(active_date_trace , date_add(day,6))>0,1,NULL)) AS user_num_6d
,COUNT(IF(date_add(day,7)<='2023-09-01' AND instr(active_date_trace , date_add(day,0))+instr(active_date_trace , date_add(day,1))+instr(active_date_trace , date_add(day,2))+instr(active_date_trace , date_add(day,3))+instr(active_date_trace , date_add(day,4))+instr(active_date_trace , date_add(day,5))+instr(active_date_trace , date_add(day,6))+instr(active_date_trace , date_add(day,7))>0,1,NULL)) AS user_num_7d
,COUNT(IF(date_add(day,8)<='2023-09-01' AND instr(active_date_trace , date_add(day,0))+instr(active_date_trace , date_add(day,1))+instr(active_date_trace , date_add(day,2))+instr(active_date_trace , date_add(day,3))+instr(active_date_trace , date_add(day,4))+instr(active_date_trace , date_add(day,5))+instr(active_date_trace , date_add(day,6))+instr(active_date_trace , date_add(day,7))+instr(active_date_trace , date_add(day,8))>0,1,NULL)) AS user_num_8d
,COUNT(IF(date_add(day,9)<='2023-09-01' AND instr(active_date_trace , date_add(day,0))+instr(active_date_trace , date_add(day,1))+instr(active_date_trace , date_add(day,2))+instr(active_date_trace , date_add(day,3))+instr(active_date_trace , date_add(day,4))+instr(active_date_trace , date_add(day,5))+instr(active_date_trace , date_add(day,6))+instr(active_date_trace , date_add(day,7))+instr(active_date_trace , date_add(day,8))+instr(active_date_trace , date_add(day,9))>0,1,NULL)) AS user_num_9d
,COUNT(IF(date_add(day,10)<='2023-09-01' AND instr(active_date_trace , date_add(day,0))+instr(active_date_trace , date_add(day,1))+instr(active_date_trace , date_add(day,2))+instr(active_date_trace , date_add(day,3))+instr(active_date_trace , date_add(day,4))+instr(active_date_trace , date_add(day,5))+instr(active_date_trace , date_add(day,6))+instr(active_date_trace , date_add(day,7))+instr(active_date_trace , date_add(day,8))+instr(active_date_trace , date_add(day,9))+instr(active_date_trace , date_add(day,10))>0,1,NULL)) AS user_num_10d
,COUNT(IF(date_add(day,11)<='2023-09-01' AND instr(active_date_trace , date_add(day,0))+instr(active_date_trace , date_add(day,1))+instr(active_date_trace , date_add(day,2))+instr(active_date_trace , date_add(day,3))+instr(active_date_trace , date_add(day,4))+instr(active_date_trace , date_add(day,5))+instr(active_date_trace , date_add(day,6))+instr(active_date_trace , date_add(day,7))+instr(active_date_trace , date_add(day,8))+instr(active_date_trace , date_add(day,9))+instr(active_date_trace , date_add(day,10))+instr(active_date_trace , date_add(day,11))>0,1,NULL)) AS user_num_11d
,COUNT(IF(date_add(day,12)<='2023-09-01' AND instr(active_date_trace , date_add(day,0))+instr(active_date_trace , date_add(day,1))+instr(active_date_trace , date_add(day,2))+instr(active_date_trace , date_add(day,3))+instr(active_date_trace , date_add(day,4))+instr(active_date_trace , date_add(day,5))+instr(active_date_trace , date_add(day,6))+instr(active_date_trace , date_add(day,7))+instr(active_date_trace , date_add(day,8))+instr(active_date_trace , date_add(day,9))+instr(active_date_trace , date_add(day,10))+instr(active_date_trace , date_add(day,11))+instr(active_date_trace , date_add(day,12))>0,1,NULL)) AS user_num_12d
,COUNT(IF(date_add(day,13)<='2023-09-01' AND instr(active_date_trace , date_add(day,0))+instr(active_date_trace , date_add(day,1))+instr(active_date_trace , date_add(day,2))+instr(active_date_trace , date_add(day,3))+instr(active_date_trace , date_add(day,4))+instr(active_date_trace , date_add(day,5))+instr(active_date_trace , date_add(day,6))+instr(active_date_trace , date_add(day,7))+instr(active_date_trace , date_add(day,8))+instr(active_date_trace , date_add(day,9))+instr(active_date_trace , date_add(day,10))+instr(active_date_trace , date_add(day,11))+instr(active_date_trace , date_add(day,12))+instr(active_date_trace , date_add(day,13))>0,1,NULL)) AS user_num_13d
,COUNT(IF(date_add(day,14)<='2023-09-01' AND instr(active_date_trace , date_add(day,0))+instr(active_date_trace , date_add(day,1))+instr(active_date_trace , date_add(day,2))+instr(active_date_trace , date_add(day,3))+instr(active_date_trace , date_add(day,4))+instr(active_date_trace , date_add(day,5))+instr(active_date_trace , date_add(day,6))+instr(active_date_trace , date_add(day,7))+instr(active_date_trace , date_add(day,8))+instr(active_date_trace , date_add(day,9))+instr(active_date_trace , date_add(day,10))+instr(active_date_trace , date_add(day,11))+instr(active_date_trace , date_add(day,12))+instr(active_date_trace , date_add(day,13))+instr(active_date_trace , date_add(day,14))>0,1,NULL)) AS user_num_14d
,COUNT(IF(date_add(day,15)<='2023-09-01' AND instr(active_date_trace , date_add(day,0))+instr(active_date_trace , date_add(day,1))+instr(active_date_trace , date_add(day,2))+instr(active_date_trace , date_add(day,3))+instr(active_date_trace , date_add(day,4))+instr(active_date_trace , date_add(day,5))+instr(active_date_trace , date_add(day,6))+instr(active_date_trace , date_add(day,7))+instr(active_date_trace , date_add(day,8))+instr(active_date_trace , date_add(day,9))+instr(active_date_trace , date_add(day,10))+instr(active_date_trace , date_add(day,11))+instr(active_date_trace , date_add(day,12))+instr(active_date_trace , date_add(day,13))+instr(active_date_trace , date_add(day,14))+instr(active_date_trace , date_add(day,15))>0,1,NULL)) AS user_num_15d
,COUNT(IF(date_add(day,16)<='2023-09-01' AND instr(active_date_trace , date_add(day,0))+instr(active_date_trace , date_add(day,1))+instr(active_date_trace , date_add(day,2))+instr(active_date_trace , date_add(day,3))+instr(active_date_trace , date_add(day,4))+instr(active_date_trace , date_add(day,5))+instr(active_date_trace , date_add(day,6))+instr(active_date_trace , date_add(day,7))+instr(active_date_trace , date_add(day,8))+instr(active_date_trace , date_add(day,9))+instr(active_date_trace , date_add(day,10))+instr(active_date_trace , date_add(day,11))+instr(active_date_trace , date_add(day,12))+instr(active_date_trace , date_add(day,13))+instr(active_date_trace , date_add(day,14))+instr(active_date_trace , date_add(day,15))+instr(active_date_trace , date_add(day,16))>0,1,NULL)) AS user_num_16d
,COUNT(IF(date_add(day,17)<='2023-09-01' AND instr(active_date_trace , date_add(day,0))+instr(active_date_trace , date_add(day,1))+instr(active_date_trace , date_add(day,2))+instr(active_date_trace , date_add(day,3))+instr(active_date_trace , date_add(day,4))+instr(active_date_trace , date_add(day,5))+instr(active_date_trace , date_add(day,6))+instr(active_date_trace , date_add(day,7))+instr(active_date_trace , date_add(day,8))+instr(active_date_trace , date_add(day,9))+instr(active_date_trace , date_add(day,10))+instr(active_date_trace , date_add(day,11))+instr(active_date_trace , date_add(day,12))+instr(active_date_trace , date_add(day,13))+instr(active_date_trace , date_add(day,14))+instr(active_date_trace , date_add(day,15))+instr(active_date_trace , date_add(day,16))+instr(active_date_trace , date_add(day,17))>0,1,NULL)) AS user_num_17d
,COUNT(IF(date_add(day,18)<='2023-09-01' AND instr(active_date_trace , date_add(day,0))+instr(active_date_trace , date_add(day,1))+instr(active_date_trace , date_add(day,2))+instr(active_date_trace , date_add(day,3))+instr(active_date_trace , date_add(day,4))+instr(active_date_trace , date_add(day,5))+instr(active_date_trace , date_add(day,6))+instr(active_date_trace , date_add(day,7))+instr(active_date_trace , date_add(day,8))+instr(active_date_trace , date_add(day,9))+instr(active_date_trace , date_add(day,10))+instr(active_date_trace , date_add(day,11))+instr(active_date_trace , date_add(day,12))+instr(active_date_trace , date_add(day,13))+instr(active_date_trace , date_add(day,14))+instr(active_date_trace , date_add(day,15))+instr(active_date_trace , date_add(day,16))+instr(active_date_trace , date_add(day,17))+instr(active_date_trace , date_add(day,18))>0,1,NULL)) AS user_num_18d
,COUNT(IF(date_add(day,19)<='2023-09-01' AND instr(active_date_trace , date_add(day,0))+instr(active_date_trace , date_add(day,1))+instr(active_date_trace , date_add(day,2))+instr(active_date_trace , date_add(day,3))+instr(active_date_trace , date_add(day,4))+instr(active_date_trace , date_add(day,5))+instr(active_date_trace , date_add(day,6))+instr(active_date_trace , date_add(day,7))+instr(active_date_trace , date_add(day,8))+instr(active_date_trace , date_add(day,9))+instr(active_date_trace , date_add(day,10))+instr(active_date_trace , date_add(day,11))+instr(active_date_trace , date_add(day,12))+instr(active_date_trace , date_add(day,13))+instr(active_date_trace , date_add(day,14))+instr(active_date_trace , date_add(day,15))+instr(active_date_trace , date_add(day,16))+instr(active_date_trace , date_add(day,17))+instr(active_date_trace , date_add(day,18))+instr(active_date_trace , date_add(day,19))>0,1,NULL)) AS user_num_19d
,COUNT(IF(date_add(day,20)<='2023-09-01' AND instr(active_date_trace , date_add(day,0))+instr(active_date_trace , date_add(day,1))+instr(active_date_trace , date_add(day,2))+instr(active_date_trace , date_add(day,3))+instr(active_date_trace , date_add(day,4))+instr(active_date_trace , date_add(day,5))+instr(active_date_trace , date_add(day,6))+instr(active_date_trace , date_add(day,7))+instr(active_date_trace , date_add(day,8))+instr(active_date_trace , date_add(day,9))+instr(active_date_trace , date_add(day,10))+instr(active_date_trace , date_add(day,11))+instr(active_date_trace , date_add(day,12))+instr(active_date_trace , date_add(day,13))+instr(active_date_trace , date_add(day,14))+instr(active_date_trace , date_add(day,15))+instr(active_date_trace , date_add(day,16))+instr(active_date_trace , date_add(day,17))+instr(active_date_trace , date_add(day,18))+instr(active_date_trace , date_add(day,19))+instr(active_date_trace , date_add(day,20))>0,1,NULL)) AS user_num_20d
,COUNT(IF(date_add(day,21)<='2023-09-01' AND instr(active_date_trace , date_add(day,0))+instr(active_date_trace , date_add(day,1))+instr(active_date_trace , date_add(day,2))+instr(active_date_trace , date_add(day,3))+instr(active_date_trace , date_add(day,4))+instr(active_date_trace , date_add(day,5))+instr(active_date_trace , date_add(day,6))+instr(active_date_trace , date_add(day,7))+instr(active_date_trace , date_add(day,8))+instr(active_date_trace , date_add(day,9))+instr(active_date_trace , date_add(day,10))+instr(active_date_trace , date_add(day,11))+instr(active_date_trace , date_add(day,12))+instr(active_date_trace , date_add(day,13))+instr(active_date_trace , date_add(day,14))+instr(active_date_trace , date_add(day,15))+instr(active_date_trace , date_add(day,16))+instr(active_date_trace , date_add(day,17))+instr(active_date_trace , date_add(day,18))+instr(active_date_trace , date_add(day,19))+instr(active_date_trace , date_add(day,20))+instr(active_date_trace , date_add(day,21))>0,1,NULL)) AS user_num_21d
,COUNT(IF(date_add(day,22)<='2023-09-01' AND instr(active_date_trace , date_add(day,0))+instr(active_date_trace , date_add(day,1))+instr(active_date_trace , date_add(day,2))+instr(active_date_trace , date_add(day,3))+instr(active_date_trace , date_add(day,4))+instr(active_date_trace , date_add(day,5))+instr(active_date_trace , date_add(day,6))+instr(active_date_trace , date_add(day,7))+instr(active_date_trace , date_add(day,8))+instr(active_date_trace , date_add(day,9))+instr(active_date_trace , date_add(day,10))+instr(active_date_trace , date_add(day,11))+instr(active_date_trace , date_add(day,12))+instr(active_date_trace , date_add(day,13))+instr(active_date_trace , date_add(day,14))+instr(active_date_trace , date_add(day,15))+instr(active_date_trace , date_add(day,16))+instr(active_date_trace , date_add(day,17))+instr(active_date_trace , date_add(day,18))+instr(active_date_trace , date_add(day,19))+instr(active_date_trace , date_add(day,20))+instr(active_date_trace , date_add(day,21))+instr(active_date_trace , date_add(day,22))>0,1,NULL)) AS user_num_22d
,COUNT(IF(date_add(day,23)<='2023-09-01' AND instr(active_date_trace , date_add(day,0))+instr(active_date_trace , date_add(day,1))+instr(active_date_trace , date_add(day,2))+instr(active_date_trace , date_add(day,3))+instr(active_date_trace , date_add(day,4))+instr(active_date_trace , date_add(day,5))+instr(active_date_trace , date_add(day,6))+instr(active_date_trace , date_add(day,7))+instr(active_date_trace , date_add(day,8))+instr(active_date_trace , date_add(day,9))+instr(active_date_trace , date_add(day,10))+instr(active_date_trace , date_add(day,11))+instr(active_date_trace , date_add(day,12))+instr(active_date_trace , date_add(day,13))+instr(active_date_trace , date_add(day,14))+instr(active_date_trace , date_add(day,15))+instr(active_date_trace , date_add(day,16))+instr(active_date_trace , date_add(day,17))+instr(active_date_trace , date_add(day,18))+instr(active_date_trace , date_add(day,19))+instr(active_date_trace , date_add(day,20))+instr(active_date_trace , date_add(day,21))+instr(active_date_trace , date_add(day,22))+instr(active_date_trace , date_add(day,23))>0,1,NULL)) AS user_num_23d
,COUNT(IF(date_add(day,24)<='2023-09-01' AND instr(active_date_trace , date_add(day,0))+instr(active_date_trace , date_add(day,1))+instr(active_date_trace , date_add(day,2))+instr(active_date_trace , date_add(day,3))+instr(active_date_trace , date_add(day,4))+instr(active_date_trace , date_add(day,5))+instr(active_date_trace , date_add(day,6))+instr(active_date_trace , date_add(day,7))+instr(active_date_trace , date_add(day,8))+instr(active_date_trace , date_add(day,9))+instr(active_date_trace , date_add(day,10))+instr(active_date_trace , date_add(day,11))+instr(active_date_trace , date_add(day,12))+instr(active_date_trace , date_add(day,13))+instr(active_date_trace , date_add(day,14))+instr(active_date_trace , date_add(day,15))+instr(active_date_trace , date_add(day,16))+instr(active_date_trace , date_add(day,17))+instr(active_date_trace , date_add(day,18))+instr(active_date_trace , date_add(day,19))+instr(active_date_trace , date_add(day,20))+instr(active_date_trace , date_add(day,21))+instr(active_date_trace , date_add(day,22))+instr(active_date_trace , date_add(day,23))+instr(active_date_trace , date_add(day,24))>0,1,NULL)) AS user_num_24d
,COUNT(IF(date_add(day,25)<='2023-09-01' AND instr(active_date_trace , date_add(day,0))+instr(active_date_trace , date_add(day,1))+instr(active_date_trace , date_add(day,2))+instr(active_date_trace , date_add(day,3))+instr(active_date_trace , date_add(day,4))+instr(active_date_trace , date_add(day,5))+instr(active_date_trace , date_add(day,6))+instr(active_date_trace , date_add(day,7))+instr(active_date_trace , date_add(day,8))+instr(active_date_trace , date_add(day,9))+instr(active_date_trace , date_add(day,10))+instr(active_date_trace , date_add(day,11))+instr(active_date_trace , date_add(day,12))+instr(active_date_trace , date_add(day,13))+instr(active_date_trace , date_add(day,14))+instr(active_date_trace , date_add(day,15))+instr(active_date_trace , date_add(day,16))+instr(active_date_trace , date_add(day,17))+instr(active_date_trace , date_add(day,18))+instr(active_date_trace , date_add(day,19))+instr(active_date_trace , date_add(day,20))+instr(active_date_trace , date_add(day,21))+instr(active_date_trace , date_add(day,22))+instr(active_date_trace , date_add(day,23))+instr(active_date_trace , date_add(day,24))+instr(active_date_trace , date_add(day,25))>0,1,NULL)) AS user_num_25d
,COUNT(IF(date_add(day,26)<='2023-09-01' AND instr(active_date_trace , date_add(day,0))+instr(active_date_trace , date_add(day,1))+instr(active_date_trace , date_add(day,2))+instr(active_date_trace , date_add(day,3))+instr(active_date_trace , date_add(day,4))+instr(active_date_trace , date_add(day,5))+instr(active_date_trace , date_add(day,6))+instr(active_date_trace , date_add(day,7))+instr(active_date_trace , date_add(day,8))+instr(active_date_trace , date_add(day,9))+instr(active_date_trace , date_add(day,10))+instr(active_date_trace , date_add(day,11))+instr(active_date_trace , date_add(day,12))+instr(active_date_trace , date_add(day,13))+instr(active_date_trace , date_add(day,14))+instr(active_date_trace , date_add(day,15))+instr(active_date_trace , date_add(day,16))+instr(active_date_trace , date_add(day,17))+instr(active_date_trace , date_add(day,18))+instr(active_date_trace , date_add(day,19))+instr(active_date_trace , date_add(day,20))+instr(active_date_trace , date_add(day,21))+instr(active_date_trace , date_add(day,22))+instr(active_date_trace , date_add(day,23))+instr(active_date_trace , date_add(day,24))+instr(active_date_trace , date_add(day,25))+instr(active_date_trace , date_add(day,26))>0,1,NULL)) AS user_num_26d
,COUNT(IF(date_add(day,27)<='2023-09-01' AND instr(active_date_trace , date_add(day,0))+instr(active_date_trace , date_add(day,1))+instr(active_date_trace , date_add(day,2))+instr(active_date_trace , date_add(day,3))+instr(active_date_trace , date_add(day,4))+instr(active_date_trace , date_add(day,5))+instr(active_date_trace , date_add(day,6))+instr(active_date_trace , date_add(day,7))+instr(active_date_trace , date_add(day,8))+instr(active_date_trace , date_add(day,9))+instr(active_date_trace , date_add(day,10))+instr(active_date_trace , date_add(day,11))+instr(active_date_trace , date_add(day,12))+instr(active_date_trace , date_add(day,13))+instr(active_date_trace , date_add(day,14))+instr(active_date_trace , date_add(day,15))+instr(active_date_trace , date_add(day,16))+instr(active_date_trace , date_add(day,17))+instr(active_date_trace , date_add(day,18))+instr(active_date_trace , date_add(day,19))+instr(active_date_trace , date_add(day,20))+instr(active_date_trace , date_add(day,21))+instr(active_date_trace , date_add(day,22))+instr(active_date_trace , date_add(day,23))+instr(active_date_trace , date_add(day,24))+instr(active_date_trace , date_add(day,25))+instr(active_date_trace , date_add(day,26))+instr(active_date_trace , date_add(day,27))>0,1,NULL)) AS user_num_27d
,COUNT(IF(date_add(day,28)<='2023-09-01' AND instr(active_date_trace , date_add(day,0))+instr(active_date_trace , date_add(day,1))+instr(active_date_trace , date_add(day,2))+instr(active_date_trace , date_add(day,3))+instr(active_date_trace , date_add(day,4))+instr(active_date_trace , date_add(day,5))+instr(active_date_trace , date_add(day,6))+instr(active_date_trace , date_add(day,7))+instr(active_date_trace , date_add(day,8))+instr(active_date_trace , date_add(day,9))+instr(active_date_trace , date_add(day,10))+instr(active_date_trace , date_add(day,11))+instr(active_date_trace , date_add(day,12))+instr(active_date_trace , date_add(day,13))+instr(active_date_trace , date_add(day,14))+instr(active_date_trace , date_add(day,15))+instr(active_date_trace , date_add(day,16))+instr(active_date_trace , date_add(day,17))+instr(active_date_trace , date_add(day,18))+instr(active_date_trace , date_add(day,19))+instr(active_date_trace , date_add(day,20))+instr(active_date_trace , date_add(day,21))+instr(active_date_trace , date_add(day,22))+instr(active_date_trace , date_add(day,23))+instr(active_date_trace , date_add(day,24))+instr(active_date_trace , date_add(day,25))+instr(active_date_trace , date_add(day,26))+instr(active_date_trace , date_add(day,27))+instr(active_date_trace , date_add(day,28))>0,1,NULL)) AS user_num_28d
,COUNT(IF(date_add(day,29)<='2023-09-01' AND instr(active_date_trace , date_add(day,0))+instr(active_date_trace , date_add(day,1))+instr(active_date_trace , date_add(day,2))+instr(active_date_trace , date_add(day,3))+instr(active_date_trace , date_add(day,4))+instr(active_date_trace , date_add(day,5))+instr(active_date_trace , date_add(day,6))+instr(active_date_trace , date_add(day,7))+instr(active_date_trace , date_add(day,8))+instr(active_date_trace , date_add(day,9))+instr(active_date_trace , date_add(day,10))+instr(active_date_trace , date_add(day,11))+instr(active_date_trace , date_add(day,12))+instr(active_date_trace , date_add(day,13))+instr(active_date_trace , date_add(day,14))+instr(active_date_trace , date_add(day,15))+instr(active_date_trace , date_add(day,16))+instr(active_date_trace , date_add(day,17))+instr(active_date_trace , date_add(day,18))+instr(active_date_trace , date_add(day,19))+instr(active_date_trace , date_add(day,20))+instr(active_date_trace , date_add(day,21))+instr(active_date_trace , date_add(day,22))+instr(active_date_trace , date_add(day,23))+instr(active_date_trace , date_add(day,24))+instr(active_date_trace , date_add(day,25))+instr(active_date_trace , date_add(day,26))+instr(active_date_trace , date_add(day,27))+instr(active_date_trace , date_add(day,28))+instr(active_date_trace , date_add(day,29))>0,1,NULL)) AS user_num_29d
,COUNT(IF(date_add(day,30)<='2023-09-01' AND instr(active_date_trace , date_add(day,0))+instr(active_date_trace , date_add(day,1))+instr(active_date_trace , date_add(day,2))+instr(active_date_trace , date_add(day,3))+instr(active_date_trace , date_add(day,4))+instr(active_date_trace , date_add(day,5))+instr(active_date_trace , date_add(day,6))+instr(active_date_trace , date_add(day,7))+instr(active_date_trace , date_add(day,8))+instr(active_date_trace , date_add(day,9))+instr(active_date_trace , date_add(day,10))+instr(active_date_trace , date_add(day,11))+instr(active_date_trace , date_add(day,12))+instr(active_date_trace , date_add(day,13))+instr(active_date_trace , date_add(day,14))+instr(active_date_trace , date_add(day,15))+instr(active_date_trace , date_add(day,16))+instr(active_date_trace , date_add(day,17))+instr(active_date_trace , date_add(day,18))+instr(active_date_trace , date_add(day,19))+instr(active_date_trace , date_add(day,20))+instr(active_date_trace , date_add(day,21))+instr(active_date_trace , date_add(day,22))+instr(active_date_trace , date_add(day,23))+instr(active_date_trace , date_add(day,24))+instr(active_date_trace , date_add(day,25))+instr(active_date_trace , date_add(day,26))+instr(active_date_trace , date_add(day,27))+instr(active_date_trace , date_add(day,28))+instr(active_date_trace , date_add(day,29))+instr(active_date_trace , date_add(day,30))>0,1,NULL)) AS user_num_30d
,COUNT(IF(date_add(day,31)<='2023-09-01' AND instr(active_date_trace , date_add(day,0))+instr(active_date_trace , date_add(day,1))+instr(active_date_trace , date_add(day,2))+instr(active_date_trace , date_add(day,3))+instr(active_date_trace , date_add(day,4))+instr(active_date_trace , date_add(day,5))+instr(active_date_trace , date_add(day,6))+instr(active_date_trace , date_add(day,7))+instr(active_date_trace , date_add(day,8))+instr(active_date_trace , date_add(day,9))+instr(active_date_trace , date_add(day,10))+instr(active_date_trace , date_add(day,11))+instr(active_date_trace , date_add(day,12))+instr(active_date_trace , date_add(day,13))+instr(active_date_trace , date_add(day,14))+instr(active_date_trace , date_add(day,15))+instr(active_date_trace , date_add(day,16))+instr(active_date_trace , date_add(day,17))+instr(active_date_trace , date_add(day,18))+instr(active_date_trace , date_add(day,19))+instr(active_date_trace , date_add(day,20))+instr(active_date_trace , date_add(day,21))+instr(active_date_trace , date_add(day,22))+instr(active_date_trace , date_add(day,23))+instr(active_date_trace , date_add(day,24))+instr(active_date_trace , date_add(day,25))+instr(active_date_trace , date_add(day,26))+instr(active_date_trace , date_add(day,27))+instr(active_date_trace , date_add(day,28))+instr(active_date_trace , date_add(day,29))+instr(active_date_trace , date_add(day,30))+instr(active_date_trace , date_add(day,31))>0,1,NULL)) AS user_num_31d
        FROM 
        (
            SELECT 
                user_id
                ,first_activate_date AS day
                ,active_date_trace
            FROM 
            (
                SELECT new.uid AS user_id,new.first_activate_date,t.active_date_trace
                FROM 
                (
                    SELECT uid, FROM_unixtime(first_activate_time, 'yyyy-MM-dd') AS first_activate_date
                    FROM user_info
                    where FROMONUNIXTIME(first_activate_time, 'yyyy-MM-dd') >= '2022-10-01'
                    AND FROMONUNIXTIME(first_activate_time, 'yyyy-MM-dd') <= '2023-09-01'
                ) new
                left join 
                (
                    SELECT user_id,active_date_trace FROM user_active_transaction
                    where partition_date = '2023-09-01'
                )t
                ON new.uid = t.user_id
                GROUP BY 1,2,3
            )t
            GROUP BY 1,2,3
        )t1
        GROUP BY 1
    )t2
)
,new_activate_transaction_retention AS (
    SELECT t2.day AS dt,'new_activate_transaction_retention' AS retention_type,user_num, user_num_0d
    , user_num_1d, user_num_2d, user_num_3d, user_num_4d, user_num_5d, user_num_6d, user_num_7d, user_num_8d
    , user_num_9d, user_num_10d, user_num_11d, user_num_12d, user_num_13d, user_num_14d, user_num_15d, user_num_16d
    , user_num_17d, user_num_18d, user_num_19d, user_num_20d, user_num_21d, user_num_22d, user_num_23d, user_num_24d
    , user_num_25d, user_num_26d, user_num_27d, user_num_28d, user_num_29d, user_num_30d, user_num_31d
    FROM
    (
        SELECT 
            t1.day 
            ,COUNT(DISTINCT user_id) AS user_num
            ,COUNT(IF(instr(transaction_date_trace,day) > 0,1,NULL)) AS user_num_0d
,COUNT(IF(date_add(day,1)<='2023-09-01' AND instr(transaction_date_trace , date_add(day,0))+instr(transaction_date_trace , date_add(day,1))>0,1,NULL)) AS user_num_1d
,COUNT(IF(date_add(day,2)<='2023-09-01' AND instr(transaction_date_trace , date_add(day,0))+instr(transaction_date_trace , date_add(day,1))+instr(transaction_date_trace , date_add(day,2))>0,1,NULL)) AS user_num_2d
,COUNT(IF(date_add(day,3)<='2023-09-01' AND instr(transaction_date_trace , date_add(day,0))+instr(transaction_date_trace , date_add(day,1))+instr(transaction_date_trace , date_add(day,2))+instr(transaction_date_trace , date_add(day,3))>0,1,NULL)) AS user_num_3d
,COUNT(IF(date_add(day,4)<='2023-09-01' AND instr(transaction_date_trace , date_add(day,0))+instr(transaction_date_trace , date_add(day,1))+instr(transaction_date_trace , date_add(day,2))+instr(transaction_date_trace , date_add(day,3))+instr(transaction_date_trace , date_add(day,4))>0,1,NULL)) AS user_num_4d
,COUNT(IF(date_add(day,5)<='2023-09-01' AND instr(transaction_date_trace , date_add(day,0))+instr(transaction_date_trace , date_add(day,1))+instr(transaction_date_trace , date_add(day,2))+instr(transaction_date_trace , date_add(day,3))+instr(transaction_date_trace , date_add(day,4))+instr(transaction_date_trace , date_add(day,5))>0,1,NULL)) AS user_num_5d
,COUNT(IF(date_add(day,6)<='2023-09-01' AND instr(transaction_date_trace , date_add(day,0))+instr(transaction_date_trace , date_add(day,1))+instr(transaction_date_trace , date_add(day,2))+instr(transaction_date_trace , date_add(day,3))+instr(transaction_date_trace , date_add(day,4))+instr(transaction_date_trace , date_add(day,5))+instr(transaction_date_trace , date_add(day,6))>0,1,NULL)) AS user_num_6d
,COUNT(IF(date_add(day,7)<='2023-09-01' AND instr(transaction_date_trace , date_add(day,0))+instr(transaction_date_trace , date_add(day,1))+instr(transaction_date_trace , date_add(day,2))+instr(transaction_date_trace , date_add(day,3))+instr(transaction_date_trace , date_add(day,4))+instr(transaction_date_trace , date_add(day,5))+instr(transaction_date_trace , date_add(day,6))+instr(transaction_date_trace , date_add(day,7))>0,1,NULL)) AS user_num_7d
,COUNT(IF(date_add(day,8)<='2023-09-01' AND instr(transaction_date_trace , date_add(day,0))+instr(transaction_date_trace , date_add(day,1))+instr(transaction_date_trace , date_add(day,2))+instr(transaction_date_trace , date_add(day,3))+instr(transaction_date_trace , date_add(day,4))+instr(transaction_date_trace , date_add(day,5))+instr(transaction_date_trace , date_add(day,6))+instr(transaction_date_trace , date_add(day,7))+instr(transaction_date_trace , date_add(day,8))>0,1,NULL)) AS user_num_8d
,COUNT(IF(date_add(day,9)<='2023-09-01' AND instr(transaction_date_trace , date_add(day,0))+instr(transaction_date_trace , date_add(day,1))+instr(transaction_date_trace , date_add(day,2))+instr(transaction_date_trace , date_add(day,3))+instr(transaction_date_trace , date_add(day,4))+instr(transaction_date_trace , date_add(day,5))+instr(transaction_date_trace , date_add(day,6))+instr(transaction_date_trace , date_add(day,7))+instr(transaction_date_trace , date_add(day,8))+instr(transaction_date_trace , date_add(day,9))>0,1,NULL)) AS user_num_9d
,COUNT(IF(date_add(day,10)<='2023-09-01' AND instr(transaction_date_trace , date_add(day,0))+instr(transaction_date_trace , date_add(day,1))+instr(transaction_date_trace , date_add(day,2))+instr(transaction_date_trace , date_add(day,3))+instr(transaction_date_trace , date_add(day,4))+instr(transaction_date_trace , date_add(day,5))+instr(transaction_date_trace , date_add(day,6))+instr(transaction_date_trace , date_add(day,7))+instr(transaction_date_trace , date_add(day,8))+instr(transaction_date_trace , date_add(day,9))+instr(transaction_date_trace , date_add(day,10))>0,1,NULL)) AS user_num_10d
,COUNT(IF(date_add(day,11)<='2023-09-01' AND instr(transaction_date_trace , date_add(day,0))+instr(transaction_date_trace , date_add(day,1))+instr(transaction_date_trace , date_add(day,2))+instr(transaction_date_trace , date_add(day,3))+instr(transaction_date_trace , date_add(day,4))+instr(transaction_date_trace , date_add(day,5))+instr(transaction_date_trace , date_add(day,6))+instr(transaction_date_trace , date_add(day,7))+instr(transaction_date_trace , date_add(day,8))+instr(transaction_date_trace , date_add(day,9))+instr(transaction_date_trace , date_add(day,10))+instr(transaction_date_trace , date_add(day,11))>0,1,NULL)) AS user_num_11d
,COUNT(IF(date_add(day,12)<='2023-09-01' AND instr(transaction_date_trace , date_add(day,0))+instr(transaction_date_trace , date_add(day,1))+instr(transaction_date_trace , date_add(day,2))+instr(transaction_date_trace , date_add(day,3))+instr(transaction_date_trace , date_add(day,4))+instr(transaction_date_trace , date_add(day,5))+instr(transaction_date_trace , date_add(day,6))+instr(transaction_date_trace , date_add(day,7))+instr(transaction_date_trace , date_add(day,8))+instr(transaction_date_trace , date_add(day,9))+instr(transaction_date_trace , date_add(day,10))+instr(transaction_date_trace , date_add(day,11))+instr(transaction_date_trace , date_add(day,12))>0,1,NULL)) AS user_num_12d
,COUNT(IF(date_add(day,13)<='2023-09-01' AND instr(transaction_date_trace , date_add(day,0))+instr(transaction_date_trace , date_add(day,1))+instr(transaction_date_trace , date_add(day,2))+instr(transaction_date_trace , date_add(day,3))+instr(transaction_date_trace , date_add(day,4))+instr(transaction_date_trace , date_add(day,5))+instr(transaction_date_trace , date_add(day,6))+instr(transaction_date_trace , date_add(day,7))+instr(transaction_date_trace , date_add(day,8))+instr(transaction_date_trace , date_add(day,9))+instr(transaction_date_trace , date_add(day,10))+instr(transaction_date_trace , date_add(day,11))+instr(transaction_date_trace , date_add(day,12))+instr(transaction_date_trace , date_add(day,13))>0,1,NULL)) AS user_num_13d
,COUNT(IF(date_add(day,14)<='2023-09-01' AND instr(transaction_date_trace , date_add(day,0))+instr(transaction_date_trace , date_add(day,1))+instr(transaction_date_trace , date_add(day,2))+instr(transaction_date_trace , date_add(day,3))+instr(transaction_date_trace , date_add(day,4))+instr(transaction_date_trace , date_add(day,5))+instr(transaction_date_trace , date_add(day,6))+instr(transaction_date_trace , date_add(day,7))+instr(transaction_date_trace , date_add(day,8))+instr(transaction_date_trace , date_add(day,9))+instr(transaction_date_trace , date_add(day,10))+instr(transaction_date_trace , date_add(day,11))+instr(transaction_date_trace , date_add(day,12))+instr(transaction_date_trace , date_add(day,13))+instr(transaction_date_trace , date_add(day,14))>0,1,NULL)) AS user_num_14d
,COUNT(IF(date_add(day,15)<='2023-09-01' AND instr(transaction_date_trace , date_add(day,0))+instr(transaction_date_trace , date_add(day,1))+instr(transaction_date_trace , date_add(day,2))+instr(transaction_date_trace , date_add(day,3))+instr(transaction_date_trace , date_add(day,4))+instr(transaction_date_trace , date_add(day,5))+instr(transaction_date_trace , date_add(day,6))+instr(transaction_date_trace , date_add(day,7))+instr(transaction_date_trace , date_add(day,8))+instr(transaction_date_trace , date_add(day,9))+instr(transaction_date_trace , date_add(day,10))+instr(transaction_date_trace , date_add(day,11))+instr(transaction_date_trace , date_add(day,12))+instr(transaction_date_trace , date_add(day,13))+instr(transaction_date_trace , date_add(day,14))+instr(transaction_date_trace , date_add(day,15))>0,1,NULL)) AS user_num_15d
,COUNT(IF(date_add(day,16)<='2023-09-01' AND instr(transaction_date_trace , date_add(day,0))+instr(transaction_date_trace , date_add(day,1))+instr(transaction_date_trace , date_add(day,2))+instr(transaction_date_trace , date_add(day,3))+instr(transaction_date_trace , date_add(day,4))+instr(transaction_date_trace , date_add(day,5))+instr(transaction_date_trace , date_add(day,6))+instr(transaction_date_trace , date_add(day,7))+instr(transaction_date_trace , date_add(day,8))+instr(transaction_date_trace , date_add(day,9))+instr(transaction_date_trace , date_add(day,10))+instr(transaction_date_trace , date_add(day,11))+instr(transaction_date_trace , date_add(day,12))+instr(transaction_date_trace , date_add(day,13))+instr(transaction_date_trace , date_add(day,14))+instr(transaction_date_trace , date_add(day,15))+instr(transaction_date_trace , date_add(day,16))>0,1,NULL)) AS user_num_16d
,COUNT(IF(date_add(day,17)<='2023-09-01' AND instr(transaction_date_trace , date_add(day,0))+instr(transaction_date_trace , date_add(day,1))+instr(transaction_date_trace , date_add(day,2))+instr(transaction_date_trace , date_add(day,3))+instr(transaction_date_trace , date_add(day,4))+instr(transaction_date_trace , date_add(day,5))+instr(transaction_date_trace , date_add(day,6))+instr(transaction_date_trace , date_add(day,7))+instr(transaction_date_trace , date_add(day,8))+instr(transaction_date_trace , date_add(day,9))+instr(transaction_date_trace , date_add(day,10))+instr(transaction_date_trace , date_add(day,11))+instr(transaction_date_trace , date_add(day,12))+instr(transaction_date_trace , date_add(day,13))+instr(transaction_date_trace , date_add(day,14))+instr(transaction_date_trace , date_add(day,15))+instr(transaction_date_trace , date_add(day,16))+instr(transaction_date_trace , date_add(day,17))>0,1,NULL)) AS user_num_17d
,COUNT(IF(date_add(day,18)<='2023-09-01' AND instr(transaction_date_trace , date_add(day,0))+instr(transaction_date_trace , date_add(day,1))+instr(transaction_date_trace , date_add(day,2))+instr(transaction_date_trace , date_add(day,3))+instr(transaction_date_trace , date_add(day,4))+instr(transaction_date_trace , date_add(day,5))+instr(transaction_date_trace , date_add(day,6))+instr(transaction_date_trace , date_add(day,7))+instr(transaction_date_trace , date_add(day,8))+instr(transaction_date_trace , date_add(day,9))+instr(transaction_date_trace , date_add(day,10))+instr(transaction_date_trace , date_add(day,11))+instr(transaction_date_trace , date_add(day,12))+instr(transaction_date_trace , date_add(day,13))+instr(transaction_date_trace , date_add(day,14))+instr(transaction_date_trace , date_add(day,15))+instr(transaction_date_trace , date_add(day,16))+instr(transaction_date_trace , date_add(day,17))+instr(transaction_date_trace , date_add(day,18))>0,1,NULL)) AS user_num_18d
,COUNT(IF(date_add(day,19)<='2023-09-01' AND instr(transaction_date_trace , date_add(day,0))+instr(transaction_date_trace , date_add(day,1))+instr(transaction_date_trace , date_add(day,2))+instr(transaction_date_trace , date_add(day,3))+instr(transaction_date_trace , date_add(day,4))+instr(transaction_date_trace , date_add(day,5))+instr(transaction_date_trace , date_add(day,6))+instr(transaction_date_trace , date_add(day,7))+instr(transaction_date_trace , date_add(day,8))+instr(transaction_date_trace , date_add(day,9))+instr(transaction_date_trace , date_add(day,10))+instr(transaction_date_trace , date_add(day,11))+instr(transaction_date_trace , date_add(day,12))+instr(transaction_date_trace , date_add(day,13))+instr(transaction_date_trace , date_add(day,14))+instr(transaction_date_trace , date_add(day,15))+instr(transaction_date_trace , date_add(day,16))+instr(transaction_date_trace , date_add(day,17))+instr(transaction_date_trace , date_add(day,18))+instr(transaction_date_trace , date_add(day,19))>0,1,NULL)) AS user_num_19d
,COUNT(IF(date_add(day,20)<='2023-09-01' AND instr(transaction_date_trace , date_add(day,0))+instr(transaction_date_trace , date_add(day,1))+instr(transaction_date_trace , date_add(day,2))+instr(transaction_date_trace , date_add(day,3))+instr(transaction_date_trace , date_add(day,4))+instr(transaction_date_trace , date_add(day,5))+instr(transaction_date_trace , date_add(day,6))+instr(transaction_date_trace , date_add(day,7))+instr(transaction_date_trace , date_add(day,8))+instr(transaction_date_trace , date_add(day,9))+instr(transaction_date_trace , date_add(day,10))+instr(transaction_date_trace , date_add(day,11))+instr(transaction_date_trace , date_add(day,12))+instr(transaction_date_trace , date_add(day,13))+instr(transaction_date_trace , date_add(day,14))+instr(transaction_date_trace , date_add(day,15))+instr(transaction_date_trace , date_add(day,16))+instr(transaction_date_trace , date_add(day,17))+instr(transaction_date_trace , date_add(day,18))+instr(transaction_date_trace , date_add(day,19))+instr(transaction_date_trace , date_add(day,20))>0,1,NULL)) AS user_num_20d
,COUNT(IF(date_add(day,21)<='2023-09-01' AND instr(transaction_date_trace , date_add(day,0))+instr(transaction_date_trace , date_add(day,1))+instr(transaction_date_trace , date_add(day,2))+instr(transaction_date_trace , date_add(day,3))+instr(transaction_date_trace , date_add(day,4))+instr(transaction_date_trace , date_add(day,5))+instr(transaction_date_trace , date_add(day,6))+instr(transaction_date_trace , date_add(day,7))+instr(transaction_date_trace , date_add(day,8))+instr(transaction_date_trace , date_add(day,9))+instr(transaction_date_trace , date_add(day,10))+instr(transaction_date_trace , date_add(day,11))+instr(transaction_date_trace , date_add(day,12))+instr(transaction_date_trace , date_add(day,13))+instr(transaction_date_trace , date_add(day,14))+instr(transaction_date_trace , date_add(day,15))+instr(transaction_date_trace , date_add(day,16))+instr(transaction_date_trace , date_add(day,17))+instr(transaction_date_trace , date_add(day,18))+instr(transaction_date_trace , date_add(day,19))+instr(transaction_date_trace , date_add(day,20))+instr(transaction_date_trace , date_add(day,21))>0,1,NULL)) AS user_num_21d
,COUNT(IF(date_add(day,22)<='2023-09-01' AND instr(transaction_date_trace , date_add(day,0))+instr(transaction_date_trace , date_add(day,1))+instr(transaction_date_trace , date_add(day,2))+instr(transaction_date_trace , date_add(day,3))+instr(transaction_date_trace , date_add(day,4))+instr(transaction_date_trace , date_add(day,5))+instr(transaction_date_trace , date_add(day,6))+instr(transaction_date_trace , date_add(day,7))+instr(transaction_date_trace , date_add(day,8))+instr(transaction_date_trace , date_add(day,9))+instr(transaction_date_trace , date_add(day,10))+instr(transaction_date_trace , date_add(day,11))+instr(transaction_date_trace , date_add(day,12))+instr(transaction_date_trace , date_add(day,13))+instr(transaction_date_trace , date_add(day,14))+instr(transaction_date_trace , date_add(day,15))+instr(transaction_date_trace , date_add(day,16))+instr(transaction_date_trace , date_add(day,17))+instr(transaction_date_trace , date_add(day,18))+instr(transaction_date_trace , date_add(day,19))+instr(transaction_date_trace , date_add(day,20))+instr(transaction_date_trace , date_add(day,21))+instr(transaction_date_trace , date_add(day,22))>0,1,NULL)) AS user_num_22d
,COUNT(IF(date_add(day,23)<='2023-09-01' AND instr(transaction_date_trace , date_add(day,0))+instr(transaction_date_trace , date_add(day,1))+instr(transaction_date_trace , date_add(day,2))+instr(transaction_date_trace , date_add(day,3))+instr(transaction_date_trace , date_add(day,4))+instr(transaction_date_trace , date_add(day,5))+instr(transaction_date_trace , date_add(day,6))+instr(transaction_date_trace , date_add(day,7))+instr(transaction_date_trace , date_add(day,8))+instr(transaction_date_trace , date_add(day,9))+instr(transaction_date_trace , date_add(day,10))+instr(transaction_date_trace , date_add(day,11))+instr(transaction_date_trace , date_add(day,12))+instr(transaction_date_trace , date_add(day,13))+instr(transaction_date_trace , date_add(day,14))+instr(transaction_date_trace , date_add(day,15))+instr(transaction_date_trace , date_add(day,16))+instr(transaction_date_trace , date_add(day,17))+instr(transaction_date_trace , date_add(day,18))+instr(transaction_date_trace , date_add(day,19))+instr(transaction_date_trace , date_add(day,20))+instr(transaction_date_trace , date_add(day,21))+instr(transaction_date_trace , date_add(day,22))+instr(transaction_date_trace , date_add(day,23))>0,1,NULL)) AS user_num_23d
,COUNT(IF(date_add(day,24)<='2023-09-01' AND instr(transaction_date_trace , date_add(day,0))+instr(transaction_date_trace , date_add(day,1))+instr(transaction_date_trace , date_add(day,2))+instr(transaction_date_trace , date_add(day,3))+instr(transaction_date_trace , date_add(day,4))+instr(transaction_date_trace , date_add(day,5))+instr(transaction_date_trace , date_add(day,6))+instr(transaction_date_trace , date_add(day,7))+instr(transaction_date_trace , date_add(day,8))+instr(transaction_date_trace , date_add(day,9))+instr(transaction_date_trace , date_add(day,10))+instr(transaction_date_trace , date_add(day,11))+instr(transaction_date_trace , date_add(day,12))+instr(transaction_date_trace , date_add(day,13))+instr(transaction_date_trace , date_add(day,14))+instr(transaction_date_trace , date_add(day,15))+instr(transaction_date_trace , date_add(day,16))+instr(transaction_date_trace , date_add(day,17))+instr(transaction_date_trace , date_add(day,18))+instr(transaction_date_trace , date_add(day,19))+instr(transaction_date_trace , date_add(day,20))+instr(transaction_date_trace , date_add(day,21))+instr(transaction_date_trace , date_add(day,22))+instr(transaction_date_trace , date_add(day,23))+instr(transaction_date_trace , date_add(day,24))>0,1,NULL)) AS user_num_24d
,COUNT(IF(date_add(day,25)<='2023-09-01' AND instr(transaction_date_trace , date_add(day,0))+instr(transaction_date_trace , date_add(day,1))+instr(transaction_date_trace , date_add(day,2))+instr(transaction_date_trace , date_add(day,3))+instr(transaction_date_trace , date_add(day,4))+instr(transaction_date_trace , date_add(day,5))+instr(transaction_date_trace , date_add(day,6))+instr(transaction_date_trace , date_add(day,7))+instr(transaction_date_trace , date_add(day,8))+instr(transaction_date_trace , date_add(day,9))+instr(transaction_date_trace , date_add(day,10))+instr(transaction_date_trace , date_add(day,11))+instr(transaction_date_trace , date_add(day,12))+instr(transaction_date_trace , date_add(day,13))+instr(transaction_date_trace , date_add(day,14))+instr(transaction_date_trace , date_add(day,15))+instr(transaction_date_trace , date_add(day,16))+instr(transaction_date_trace , date_add(day,17))+instr(transaction_date_trace , date_add(day,18))+instr(transaction_date_trace , date_add(day,19))+instr(transaction_date_trace , date_add(day,20))+instr(transaction_date_trace , date_add(day,21))+instr(transaction_date_trace , date_add(day,22))+instr(transaction_date_trace , date_add(day,23))+instr(transaction_date_trace , date_add(day,24))+instr(transaction_date_trace , date_add(day,25))>0,1,NULL)) AS user_num_25d
,COUNT(IF(date_add(day,26)<='2023-09-01' AND instr(transaction_date_trace , date_add(day,0))+instr(transaction_date_trace , date_add(day,1))+instr(transaction_date_trace , date_add(day,2))+instr(transaction_date_trace , date_add(day,3))+instr(transaction_date_trace , date_add(day,4))+instr(transaction_date_trace , date_add(day,5))+instr(transaction_date_trace , date_add(day,6))+instr(transaction_date_trace , date_add(day,7))+instr(transaction_date_trace , date_add(day,8))+instr(transaction_date_trace , date_add(day,9))+instr(transaction_date_trace , date_add(day,10))+instr(transaction_date_trace , date_add(day,11))+instr(transaction_date_trace , date_add(day,12))+instr(transaction_date_trace , date_add(day,13))+instr(transaction_date_trace , date_add(day,14))+instr(transaction_date_trace , date_add(day,15))+instr(transaction_date_trace , date_add(day,16))+instr(transaction_date_trace , date_add(day,17))+instr(transaction_date_trace , date_add(day,18))+instr(transaction_date_trace , date_add(day,19))+instr(transaction_date_trace , date_add(day,20))+instr(transaction_date_trace , date_add(day,21))+instr(transaction_date_trace , date_add(day,22))+instr(transaction_date_trace , date_add(day,23))+instr(transaction_date_trace , date_add(day,24))+instr(transaction_date_trace , date_add(day,25))+instr(transaction_date_trace , date_add(day,26))>0,1,NULL)) AS user_num_26d
,COUNT(IF(date_add(day,27)<='2023-09-01' AND instr(transaction_date_trace , date_add(day,0))+instr(transaction_date_trace , date_add(day,1))+instr(transaction_date_trace , date_add(day,2))+instr(transaction_date_trace , date_add(day,3))+instr(transaction_date_trace , date_add(day,4))+instr(transaction_date_trace , date_add(day,5))+instr(transaction_date_trace , date_add(day,6))+instr(transaction_date_trace , date_add(day,7))+instr(transaction_date_trace , date_add(day,8))+instr(transaction_date_trace , date_add(day,9))+instr(transaction_date_trace , date_add(day,10))+instr(transaction_date_trace , date_add(day,11))+instr(transaction_date_trace , date_add(day,12))+instr(transaction_date_trace , date_add(day,13))+instr(transaction_date_trace , date_add(day,14))+instr(transaction_date_trace , date_add(day,15))+instr(transaction_date_trace , date_add(day,16))+instr(transaction_date_trace , date_add(day,17))+instr(transaction_date_trace , date_add(day,18))+instr(transaction_date_trace , date_add(day,19))+instr(transaction_date_trace , date_add(day,20))+instr(transaction_date_trace , date_add(day,21))+instr(transaction_date_trace , date_add(day,22))+instr(transaction_date_trace , date_add(day,23))+instr(transaction_date_trace , date_add(day,24))+instr(transaction_date_trace , date_add(day,25))+instr(transaction_date_trace , date_add(day,26))+instr(transaction_date_trace , date_add(day,27))>0,1,NULL)) AS user_num_27d
,COUNT(IF(date_add(day,28)<='2023-09-01' AND instr(transaction_date_trace , date_add(day,0))+instr(transaction_date_trace , date_add(day,1))+instr(transaction_date_trace , date_add(day,2))+instr(transaction_date_trace , date_add(day,3))+instr(transaction_date_trace , date_add(day,4))+instr(transaction_date_trace , date_add(day,5))+instr(transaction_date_trace , date_add(day,6))+instr(transaction_date_trace , date_add(day,7))+instr(transaction_date_trace , date_add(day,8))+instr(transaction_date_trace , date_add(day,9))+instr(transaction_date_trace , date_add(day,10))+instr(transaction_date_trace , date_add(day,11))+instr(transaction_date_trace , date_add(day,12))+instr(transaction_date_trace , date_add(day,13))+instr(transaction_date_trace , date_add(day,14))+instr(transaction_date_trace , date_add(day,15))+instr(transaction_date_trace , date_add(day,16))+instr(transaction_date_trace , date_add(day,17))+instr(transaction_date_trace , date_add(day,18))+instr(transaction_date_trace , date_add(day,19))+instr(transaction_date_trace , date_add(day,20))+instr(transaction_date_trace , date_add(day,21))+instr(transaction_date_trace , date_add(day,22))+instr(transaction_date_trace , date_add(day,23))+instr(transaction_date_trace , date_add(day,24))+instr(transaction_date_trace , date_add(day,25))+instr(transaction_date_trace , date_add(day,26))+instr(transaction_date_trace , date_add(day,27))+instr(transaction_date_trace , date_add(day,28))>0,1,NULL)) AS user_num_28d
,COUNT(IF(date_add(day,29)<='2023-09-01' AND instr(transaction_date_trace , date_add(day,0))+instr(transaction_date_trace , date_add(day,1))+instr(transaction_date_trace , date_add(day,2))+instr(transaction_date_trace , date_add(day,3))+instr(transaction_date_trace , date_add(day,4))+instr(transaction_date_trace , date_add(day,5))+instr(transaction_date_trace , date_add(day,6))+instr(transaction_date_trace , date_add(day,7))+instr(transaction_date_trace , date_add(day,8))+instr(transaction_date_trace , date_add(day,9))+instr(transaction_date_trace , date_add(day,10))+instr(transaction_date_trace , date_add(day,11))+instr(transaction_date_trace , date_add(day,12))+instr(transaction_date_trace , date_add(day,13))+instr(transaction_date_trace , date_add(day,14))+instr(transaction_date_trace , date_add(day,15))+instr(transaction_date_trace , date_add(day,16))+instr(transaction_date_trace , date_add(day,17))+instr(transaction_date_trace , date_add(day,18))+instr(transaction_date_trace , date_add(day,19))+instr(transaction_date_trace , date_add(day,20))+instr(transaction_date_trace , date_add(day,21))+instr(transaction_date_trace , date_add(day,22))+instr(transaction_date_trace , date_add(day,23))+instr(transaction_date_trace , date_add(day,24))+instr(transaction_date_trace , date_add(day,25))+instr(transaction_date_trace , date_add(day,26))+instr(transaction_date_trace , date_add(day,27))+instr(transaction_date_trace , date_add(day,28))+instr(transaction_date_trace , date_add(day,29))>0,1,NULL)) AS user_num_29d
,COUNT(IF(date_add(day,30)<='2023-09-01' AND instr(transaction_date_trace , date_add(day,0))+instr(transaction_date_trace , date_add(day,1))+instr(transaction_date_trace , date_add(day,2))+instr(transaction_date_trace , date_add(day,3))+instr(transaction_date_trace , date_add(day,4))+instr(transaction_date_trace , date_add(day,5))+instr(transaction_date_trace , date_add(day,6))+instr(transaction_date_trace , date_add(day,7))+instr(transaction_date_trace , date_add(day,8))+instr(transaction_date_trace , date_add(day,9))+instr(transaction_date_trace , date_add(day,10))+instr(transaction_date_trace , date_add(day,11))+instr(transaction_date_trace , date_add(day,12))+instr(transaction_date_trace , date_add(day,13))+instr(transaction_date_trace , date_add(day,14))+instr(transaction_date_trace , date_add(day,15))+instr(transaction_date_trace , date_add(day,16))+instr(transaction_date_trace , date_add(day,17))+instr(transaction_date_trace , date_add(day,18))+instr(transaction_date_trace , date_add(day,19))+instr(transaction_date_trace , date_add(day,20))+instr(transaction_date_trace , date_add(day,21))+instr(transaction_date_trace , date_add(day,22))+instr(transaction_date_trace , date_add(day,23))+instr(transaction_date_trace , date_add(day,24))+instr(transaction_date_trace , date_add(day,25))+instr(transaction_date_trace , date_add(day,26))+instr(transaction_date_trace , date_add(day,27))+instr(transaction_date_trace , date_add(day,28))+instr(transaction_date_trace , date_add(day,29))+instr(transaction_date_trace , date_add(day,30))>0,1,NULL)) AS user_num_30d
,COUNT(IF(date_add(day,31)<='2023-09-01' AND instr(transaction_date_trace , date_add(day,0))+instr(transaction_date_trace , date_add(day,1))+instr(transaction_date_trace , date_add(day,2))+instr(transaction_date_trace , date_add(day,3))+instr(transaction_date_trace , date_add(day,4))+instr(transaction_date_trace , date_add(day,5))+instr(transaction_date_trace , date_add(day,6))+instr(transaction_date_trace , date_add(day,7))+instr(transaction_date_trace , date_add(day,8))+instr(transaction_date_trace , date_add(day,9))+instr(transaction_date_trace , date_add(day,10))+instr(transaction_date_trace , date_add(day,11))+instr(transaction_date_trace , date_add(day,12))+instr(transaction_date_trace , date_add(day,13))+instr(transaction_date_trace , date_add(day,14))+instr(transaction_date_trace , date_add(day,15))+instr(transaction_date_trace , date_add(day,16))+instr(transaction_date_trace , date_add(day,17))+instr(transaction_date_trace , date_add(day,18))+instr(transaction_date_trace , date_add(day,19))+instr(transaction_date_trace , date_add(day,20))+instr(transaction_date_trace , date_add(day,21))+instr(transaction_date_trace , date_add(day,22))+instr(transaction_date_trace , date_add(day,23))+instr(transaction_date_trace , date_add(day,24))+instr(transaction_date_trace , date_add(day,25))+instr(transaction_date_trace , date_add(day,26))+instr(transaction_date_trace , date_add(day,27))+instr(transaction_date_trace , date_add(day,28))+instr(transaction_date_trace , date_add(day,29))+instr(transaction_date_trace , date_add(day,30))+instr(transaction_date_trace , date_add(day,31))>0,1,NULL)) AS user_num_31d        
FROM 
(
            SELECT 
                user_id
                ,first_activate_date AS day
                ,transaction_date_trace
            FROM 
            (
                SELECT new.uid AS user_id,new.first_activate_date,t.transaction_date_trace
                FROM 
                (
                    SELECT uid, FROM_unixtime(first_activate_time, 'yyyy-MM-dd') AS first_activate_date
                    FROM user_info
                    where FROM_unixtime(first_activate_time, 'yyyy-MM-dd') >= '2022-10-01'
                    AND FROM_unixtime(first_activate_time, 'yyyy-MM-dd') <= '2023-09-01'
                ) new
                left join 
                (
                    SELECT user_id,transaction_date_trace FROM user_active_transaction
                    where partition_date = '2023-09-01'
                    AND last_transaction_date is not NULL 
                )t
                ON new.uid = t.user_id
                GROUP BY 1,2,3
            )t 
            GROUP BY 1,2,3
        )t1
        GROUP BY 1
    )t2
)

INSERT OVERWRITE TABLE result
SELECT *
FROM new_activate_active_retention
UNION ALL
SELECT *
FROM new_activate_transaction_retention;


-- 优化后
-- 1.放大Driver内存

--conf spark.driver.memory=64g \ # 方法Driver的内存
--conf spark.executor.memoryOverhead=12g


-- 2.关闭codegen.wholeStage
SET spark.sql.codegen.wholeStage=FALSE;


-- 3.关闭公共表达式消除的选项
SET spark.sql.subexpressionElimination.enabled=FALSE;
